name: CI IT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1,3,5'

jobs:
  k8s-it:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s_version: [ 'v1.23.17', 'v1.24.12', 'v1.25.8', 'v1.26.4' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: jvalkeal/setup-maven@v1
        with:
          maven-version: 3.8.3
      - name: 'Install minikube ${{ matrix.k8s_version }}'
        shell: bash
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/${{ matrix.k8s_version }}/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # build
      - name: Build
        run: |
          mvn -U -B -Pfailsafe verify -pl spring-cloud-deployer-kubernetes
      # clean m2 cache
      - name: Clean cache
        run: |
          find ~/.m2/repository -type d -name '*SNAPSHOT' | xargs rm -fr